### PR TITLE
Vault status tool

### PR DESCRIPTION
**Pull request by reavdhoef**
https://jira.uu.nl/browse/YDA-4112

Use with:
irule -r irods_rule_engine_plugin-python-instance -F /etc/irods/irods-ruleset-uu/tools/vault-status-check.r

### CODE REVIEW

**Review by lwesterhof — APPROVED** [review]
LGTM, can be merged if Rob and Sietse agree with implemented functionality.

Can you add a header with the usage of the script?

**Review by stsnel — APPROVED** [review]
LGTM  (including functionality)

**Comment by reavdhoef** [comment]
> 
> 
> LGTM, can be merged if Rob and Sietse agree with implemented functionality.
> 
> Can you add a header with the usage of the script?

Added some usage info to the header. Could not find an example for a rule file in python; is this what you had in mind?

**Review by lwesterhof — APPROVED** [review]
Yes, ready to merge.

**Pull request merged**
